language: node_js
node_js:
  - 12
cache:
  npm: true
script: npm run build
deploy:
  - app_name: cablecard-cct
    provider: cloudfoundry
    username: apikey
    password: $BLUEMIX_API
    api: https://api.eu-de.bluemix.net
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: development
  - app_name: cablecard-cct-api
    provider: cloudfoundry
    username: apikey
    password: $BLUEMIX_API
    api: https://api.eu-de.bluemix.net
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: development
